# Generated by Django 5.2 on 2025-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
