# Generated by Django 5.2 on 2025-05-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_diseasedetection_diagnosisrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='uploaded_file',
        ),
    ]
